name: cd

on:
  push:
    branches: ['releases-*' ]

jobs:
  build-n-publish:
    runs-on: ubuntu-18.04
    name: Build and deploying docs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "notesforamit@gmail.com"
          git config --global user.name "Amit Joshi"    

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pypa/build
        run: >- 
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution 📦 to Jfrog Artifactory
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_JFROG_API_TOKEN }}
          repository_url: https://artifactory.boschdevcloud.com/ui/repos/tree/General/gs-pj-top98-ai-know-pypi-aibse-local/
